# ================================================================
# src/detectors/llm_detector/prompts.py
# All zero-shot, few-shot, and CoT prompt builders
# ================================================================
# Naming convention where models share function names:
#   qwen1p5b_* → Qwen2.5-1.5B  (yes=AI, no=human — standard polarity)
#   qwen_*     → Qwen2.5-7B    (yes=human, no=AI  — swapped polarity)
#   qwen14_*   → Qwen2.5-14B   (yes=human, no=AI  — swapped polarity)
#   llama2_*   → LLaMA-2-13B   (yes=human, no=AI  — swapped polarity)
#   tinyllama_*→ TinyLlama-1.1B
#   build_*    → GPT-4o-mini
# ================================================================

import pandas as pd

SEED   = 42
K_SHOT = 3


# ================================================================
# SECTION A: TinyLlama-1.1B
# Polarity: yes=AI, no=human (standard)
# ================================================================

def tinyllama_zero_shot(text, tokenizer):
    user = (
        'Read the text below and answer the question.\n'
        'Question: Was this text generated by an AI language model?\n\n'
        f'Text:\n"""{text[:400]}"""\n\n'
        'Answer yes if AI-generated, no if human-written.'
    )
    msgs = [{'role': 'user', 'content': user}]
    prompt = tokenizer.apply_chat_template(
        msgs, tokenize=False, add_generation_prompt=True)
    return prompt + 'Answer:'


def tinyllama_few_shot(text, tokenizer, examples_df, k=K_SHOT):
    examples = examples_df.sample(k, random_state=SEED)
    shots = ''
    for _, row in examples.iterrows():
        ans = 'yes' if row['label'] == 'llm' else 'no'
        shots += f'Text: "{row["text"][:200]}"\nAI-generated? {ans}\n\n'
    user = (
        'Read each text and say yes (AI-generated) or no (human-written).\n\n'
        f'Examples:\n{shots}'
        f'Now answer:\nText: "{text[:400]}"\n'
        'AI-generated?'
    )
    msgs = [{'role': 'user', 'content': user}]
    prompt = tokenizer.apply_chat_template(
        msgs, tokenize=False, add_generation_prompt=True)
    return prompt + 'Answer:'


# ================================================================
# SECTION B: Qwen2.5-1.5B
# Polarity: yes=AI, no=human (standard)
# ================================================================

def qwen1p5b_zero_shot(text, tokenizer):
    msgs = [
        {
            'role': 'system',
            'content': (
                'You detect AI-generated text. '
                'Answer with ONE word only: yes or no. '
                'yes = AI-generated. no = human-written.'
            )
        },
        {
            'role': 'user',
            'content': (
                'Was this text generated by an AI language model?\n\n'
                f'Text:\n"""{text[:500]}"""\n\n'
                'Answer yes or no.'
            )
        }
    ]
    prompt = tokenizer.apply_chat_template(
        msgs, tokenize=False, add_generation_prompt=True)
    return prompt + 'Answer:'


def qwen1p5b_few_shot(text, tokenizer, examples_df, k=K_SHOT):
    examples = examples_df.sample(k, random_state=SEED)
    shots = ''
    for _, row in examples.iterrows():
        ans = 'yes' if row['label'] == 'llm' else 'no'
        shots += f'Text: "{row["text"][:250]}"\nAI-generated? {ans}\n\n'
    msgs = [
        {
            'role': 'system',
            'content': (
                'You detect AI-generated text. '
                'Answer with ONE word only: yes or no. '
                'yes = AI-generated. no = human-written.'
            )
        },
        {
            'role': 'user',
            'content': (
                f'Examples:\n{shots}'
                f'Now answer:\nText: "{text[:500]}"\n'
                'AI-generated? yes or no.'
            )
        }
    ]
    prompt = tokenizer.apply_chat_template(
        msgs, tokenize=False, add_generation_prompt=True)
    return prompt + 'Answer:'


# ================================================================
# SECTION C: Qwen2.5-7B
# Polarity: yes=human, no=AI (SWAPPED — Qwen has strong no-bias)
# flip=False → P(llm) = P(no) directly
# ================================================================

def qwen_zero_shot(text, tokenizer):
    msgs = [
        {
            'role': 'system',
            'content': (
                'You detect AI-generated text. '
                'Answer with ONE word only: yes or no. '
                'yes = human-written. no = AI-generated. '
                'No explanation. No punctuation. One word.'
            )
        },
        {
            'role': 'user',
            'content': (
                'Was this text written by a human?\n\n'
                f'Text:\n"""{text[:600]}"""\n\n'
                'Answer yes or no.'
            )
        }
    ]
    prompt = tokenizer.apply_chat_template(
        msgs, tokenize=False, add_generation_prompt=True)
    return prompt + 'Answer:'


def qwen_few_shot(text, tokenizer, examples_df, k=K_SHOT,
                  idx=0, retriever=None):
    from src.detectors.llm_detector.models import retrieve_shots
    if retriever is not None:
        vec, matrix, pool_df = retriever
        examples = retrieve_shots(text, pool_df, vec, matrix, k)
    else:
        examples = examples_df.sample(k, random_state=idx)

    shots = ''
    for _, row in examples.iterrows():
        # yes=human, no=AI — swapped polarity
        ans = 'no' if row['label'] == 'llm' else 'yes'
        shots += f'Text: "{row["text"][:250]}"\nHuman-written? {ans}\n\n'

    msgs = [
        {
            'role': 'system',
            'content': (
                'You detect AI-generated text. '
                'Answer with ONE word only: yes or no. '
                'yes = human-written. no = AI-generated.'
            )
        },
        {
            'role': 'user',
            'content': (
                f'Examples:\n{shots}'
                f'Now answer:\nText: "{text[:600]}"\n'
                'Human-written? yes or no.'
            )
        }
    ]
    prompt = tokenizer.apply_chat_template(
        msgs, tokenize=False, add_generation_prompt=True)
    return prompt + 'Answer:'


def qwen_cot_reasoning(text, tokenizer):
    msgs = [
        {
            'role': 'system',
            'content': (
                'You are an expert forensic linguist. '
                'Your task is to determine whether a passage was written '
                'by a human or generated by an AI language model '
                '(including ChatGPT, GPT-4, Claude, Llama, Qwen, etc.). '
                'Think carefully and be precise.'
            )
        },
        {
            'role': 'user',
            'content': (
                'Analyse whether this passage was written by a HUMAN or an AI.\n\n'
                f'Passage:\n"""{text[:700]}"""\n\n'
                'Evaluate each dimension and score it 0 (strongly human) '
                'to 10 (strongly AI):\n\n'
                '1. STRUCTURE: Is the answer neatly organised with clear sections '
                '   or numbered points? (AI: high structure, even in short answers)\n'
                '2. COMPLETENESS: Does it cover the topic comprehensively without '
                '   leaving obvious gaps? (AI tends to be thorough)\n'
                '3. HEDGING: Does it acknowledge uncertainty or say "I\'m not sure"? '
                '   (Humans hedge more; AI often sounds authoritative)\n'
                '4. PERSONAL VOICE: Any personal opinions, anecdotes, slang, '
                '   contractions, typos, or tangents? (Human markers)\n'
                '5. LEXICAL RANGE: Does it use broad, polished vocabulary '
                '   even in casual answers? (AI marker)\n'
                '6. RESPONSE FIT: Does it directly and completely address the '
                '   implied question, or does it wander? (AI: tight structured fit)\n'
                '7. SHORT-FORM TELLS: Even if short, does it feel generated — '
                '   e.g., starts with "Certainly!", restates the question, '
                '   gives a mini-essay for a simple prompt, or has an '
                '   unnaturally tidy closing sentence?\n\n'
                'IMPORTANT: ChatGPT/LLM answers can be SHORT and still feel '
                'generated. Do not assume short = human.\n\n'
                'After scoring each dimension, compute:\n'
                '  AI_CONFIDENCE = average of your 7 scores (0-10 scale)\n\n'
                'State your verdict on the LAST TWO LINES as exactly:\n'
                'AI_CONFIDENCE: <number 0-10>\n'
                'VERDICT: yes   (if AI-generated)\n'
                'VERDICT: no    (if human-written)\n'
                '(Only one VERDICT line.)'
            )
        }
    ]
    return tokenizer.apply_chat_template(
        msgs, tokenize=False, add_generation_prompt=True)


# ================================================================
# SECTION D: LLaMA-2-13B
# Polarity: yes=human, no=AI (SWAPPED — LLaMA-2 has strong no-bias)
# flip=False → P(llm) = P(no) directly
# Framed as "linguistics research" to avoid safety refusals
# ================================================================

def _apply_template(msgs, tokenizer):
    """
    Use apply_chat_template if present.
    Fall back to manual LLaMA-2 [INST] format if not.
    """
    if tokenizer.chat_template:
        return tokenizer.apply_chat_template(
            msgs, tokenize=False, add_generation_prompt=True)
    # Manual LLaMA-2 chat format
    prompt = ''
    system_msg = next(
        (m['content'] for m in msgs if m['role'] == 'system'), None)
    for m in msgs:
        if m['role'] == 'system':
            continue
        elif m['role'] == 'user':
            if system_msg:
                prompt += (f"[INST] <<SYS>>\n{system_msg}\n<</SYS>>"
                           f"\n\n{m['content']} [/INST]")
                system_msg = None
            else:
                prompt += f"[INST] {m['content']} [/INST]"
        elif m['role'] == 'assistant':
            prompt += f" {m['content']} "
    return prompt


def llama2_zero_shot(text, tokenizer):
    msgs = [
        {
            'role': 'system',
            'content': (
                'You are a linguistics researcher studying writing styles. '
                'Answer with ONE word only: yes or no. '
                'yes = written by a human. '
                'no = written by an AI system. '
                'No explanation. No punctuation. One word only.'
            )
        },
        {
            'role': 'user',
            'content': (
                'Was this text written by a human?\n\n'
                f'Text sample:\n"""{text[:600]}"""\n\n'
                'Answer yes or no.'
            )
        }
    ]
    prompt = _apply_template(msgs, tokenizer)
    return prompt + 'Answer:'


def llama2_few_shot(text, tokenizer, examples_df, k=K_SHOT,
                    idx=0, retriever=None):
    from src.detectors.llm_detector.models import retrieve_shots
    if retriever is not None:
        vec, matrix, pool_df = retriever
        examples = retrieve_shots(text, pool_df, vec, matrix, k)
    else:
        examples = examples_df.sample(k, random_state=idx)

    shots = ''
    for _, row in examples.iterrows():
        # yes=human, no=AI (swapped polarity)
        ans = 'no' if row['label'] == 'llm' else 'yes'
        shots += f'Text: "{row["text"][:250]}"\nWritten by human? {ans}\n\n'

    msgs = [
        {
            'role': 'system',
            'content': (
                'You are a linguistics researcher studying writing styles. '
                'Study the labeled examples below, then answer for the new text. '
                'Respond with ONE word only: yes or no. '
                'yes = human-written. no = AI-written.'
            )
        },
        {
            'role': 'user',
            'content': (
                f'Labeled examples:\n{shots}'
                f'New text: "{text[:600]}"\n'
                'Written by human? yes or no.'
            )
        }
    ]
    prompt = _apply_template(msgs, tokenizer)
    return prompt + 'Answer:'


def llama2_cot_reasoning(text, tokenizer):
    msgs = [
        {
            'role': 'system',
            'content': (
                'You are an expert in stylometric analysis and '
                'authorship attribution. '
                'Analyse writing samples systematically to determine '
                'whether they were written by a human or an AI '
                'language model. Be precise and analytical. '
                'Always complete your analysis and always end with '
                'the AI_CONFIDENCE score and VERDICT line.'
            )
        },
        {
            'role': 'user',
            'content': (
                'Perform a stylometric analysis of this writing sample.\n\n'
                f'Sample:\n"""{text[:700]}"""\n\n'
                'Score each dimension from 0 (strongly human) '
                'to 10 (strongly AI):\n\n'
                '1. STRUCTURAL REGULARITY: uniform sentence length, '
                'predictable paragraph transitions?\n'
                '2. LEXICAL POLISH: consistently formal/polished '
                'vocabulary even in casual topics?\n'
                '3. TOPIC COVERAGE: suspiciously complete, covering '
                'all sub-aspects of the question?\n'
                '4. HEDGING STYLE: confident and authoritative vs '
                'uncertain and personal?\n'
                '5. PERSONAL MARKERS: opinions, anecdotes, typos, '
                'contractions, informal phrasing?\n'
                '6. RESPONSE ALIGNMENT: tightly matches the implied '
                'question without wandering?\n'
                '7. FORMULAIC OPENING: starts with "Certainly!", '
                '"Great question!", or restates the question?\n\n'
                'Note: Short answers can still be AI-generated. '
                'Do not assume brevity implies human authorship.\n\n'
                'After scoring all 7 dimensions write EXACTLY these '
                'two lines as the final output:\n'
                'AI_CONFIDENCE: <average of your 7 scores, 0-10>\n'
                'VERDICT: yes   (if AI-generated)\n'
                'VERDICT: no    (if human-written)\n'
                '(One VERDICT line only.)'
            )
        }
    ]
    return _apply_template(msgs, tokenizer)


# ================================================================
# SECTION E: Qwen2.5-14B
# Polarity: yes=human, no=AI (SWAPPED — same as Qwen7B)
# Stronger prompts than 7B to prevent 90% unknown rate
# ================================================================

def qwen14_zero_shot(text, tokenizer):
    msgs = [
        {
            'role': 'system',
            'content': (
                'You are an expert in authorship attribution and '
                'AI-generated text analysis. '
                'Answer with ONE word only: yes or no. '
                'yes = human-written. no = AI-generated. '
                'No explanation. No punctuation. One word.'
            )
        },
        {
            'role': 'user',
            'content': (
                'Was this text written by a human?\n\n'
                f'Text:\n"""{text[:700]}"""\n\n'
                'Answer yes or no.'
            )
        }
    ]
    prompt = tokenizer.apply_chat_template(
        msgs, tokenize=False, add_generation_prompt=True)
    return prompt + 'Answer:'


def qwen14_few_shot(text, tokenizer, examples_df, k=K_SHOT,
                    idx=0, retriever=None):
    from src.detectors.llm_detector.models import retrieve_shots
    if retriever is not None:
        vec, matrix, pool_df = retriever
        examples = retrieve_shots(text, pool_df, vec, matrix, k)
    else:
        examples = examples_df.sample(k, random_state=idx)

    shots = ''
    for _, row in examples.iterrows():
        # yes=human, no=AI (swapped — no annotations to avoid logit bias)
        ans = 'no' if row['label'] == 'llm' else 'yes'
        shots += f'Text: "{row["text"][:250]}"\nHuman-written? {ans}\n\n'

    msgs = [
        {
            'role': 'system',
            'content': (
                'You are an expert in authorship attribution. '
                'Study the labeled examples, then answer for the new text. '
                'Answer with ONE word only: yes or no. '
                'yes = human-written. no = AI-generated.'
            )
        },
        {
            'role': 'user',
            'content': (
                f'Labeled examples:\n{shots}'
                f'New text: "{text[:700]}"\n'
                'Human-written? yes or no.'
            )
        }
    ]
    prompt = tokenizer.apply_chat_template(
        msgs, tokenize=False, add_generation_prompt=True)
    return prompt + 'Answer:'


def qwen14_cot_reasoning(text, tokenizer):
    # Key differences from 7B:
    # 1. "ALWAYS complete" in system — prevents early stop
    # 2. "no exceptions" on last two lines — reduces unknown rate
    # 3. "Begin your analysis now:" — prevents refusal/hedging
    msgs = [
        {
            'role': 'system',
            'content': (
                'You are an expert forensic linguist performing '
                'authorship attribution analysis. '
                'You ALWAYS complete your full analysis and ALWAYS end '
                'with the AI_CONFIDENCE score and VERDICT line. '
                'Never leave your analysis incomplete or refuse to give a verdict.'
            )
        },
        {
            'role': 'user',
            'content': (
                'Analyse this passage to determine if it was written by '
                'a HUMAN or generated by an AI language model '
                '(ChatGPT, GPT-4, Claude, Qwen, Llama, etc.).\n\n'
                f'Passage:\n"""{text[:700]}"""\n\n'
                'Score each dimension 0 (strongly human) to 10 (strongly AI):\n\n'
                '1. STRUCTURE (0-10): Organised with clear sections/numbered points?\n'
                '2. COMPLETENESS (0-10): Covers the topic without obvious gaps?\n'
                '3. HEDGING (0-10): Confident authoritative tone, lacks uncertainty?\n'
                '4. PERSONAL VOICE (0-10): Lacks personal opinions/anecdotes/typos?\n'
                '5. LEXICAL POLISH (0-10): Uniformly formal/polished vocabulary?\n'
                '6. RESPONSE FIT (0-10): Directly and completely addresses question?\n'
                '7. FORMULAIC TELLS (0-10): Restates question, "Certainly!", '
                'unnaturally tidy closing?\n\n'
                'IMPORTANT: Short texts CAN be AI-generated. '
                'Score all 7 dimensions regardless of text length.\n\n'
                'You MUST end your response with EXACTLY these two lines '
                '(no exceptions, no additional text after):\n'
                'AI_CONFIDENCE: <your average score 0-10>\n'
                'VERDICT: yes\n'
                '--- OR ---\n'
                'AI_CONFIDENCE: <your average score 0-10>\n'
                'VERDICT: no\n\n'
                'Begin your analysis now:'
            )
        }
    ]
    return tokenizer.apply_chat_template(
        msgs, tokenize=False, add_generation_prompt=True)


# ================================================================
# SECTION F: GPT-4o-mini
# Scoring: AI_SCORE (0=human, 100=AI) — no polarity inversion
# 7-dimension reasoning chain breaks RLHF suppression
# ================================================================

def build_zero_shot(text: str) -> list:
    """
    7-dimension scoring forces granular commitment before final score.
    ~350 input + 180 output tokens per call.
    """
    return [
        {
            "role": "system",
            "content": (
                "You are an expert forensic linguist specialising in "
                "authorship attribution. "
                "AI-generated text is very common — including short, "
                "conversational-looking text from older models like "
                "ChatGPT-3.5. "
                "Score honestly based on the dimensions provided. "
                "Use the full 0-10 range for each dimension. "
                "Complete every analysis."
            )
        },
        {
            "role": "user",
            "content": (
                "Score this passage on each dimension from "
                "0 (strongly human) to 10 (strongly AI).\n\n"
                f"Passage:\n```\n{text[:800]}\n```\n\n"
                "Score each dimension (write the integer after the colon):\n"
                "1. HEDGING/FORMULAIC: Uses 'it is important', 'certainly', "
                "numbered sections, or safe generalisations: "
                "0=none, 10=throughout\n"
                "2. COMPLETENESS: Covers every sub-angle of the topic "
                "even when not asked: 0=partial, 10=exhaustive\n"
                "3. PERSONAL VOICE: Has opinions, errors, tangents, "
                "or emotional register: 0=strong personal voice, "
                "10=completely impersonal\n"
                "4. LEXICAL UNIFORMITY: Vocabulary register stays "
                "perfectly consistent throughout: 0=varied/informal, "
                "10=uniform polish\n"
                "5. STRUCTURAL NEATNESS: Clear intro/body/conclusion "
                "or logical flow: 0=rambling, 10=perfectly structured\n"
                "6. RESPONSE FIT: Directly and precisely addresses "
                "the apparent question: 0=wanders, 10=perfectly on-topic\n"
                "7. FORMULAIC TELLS: Restates question, tidy closing, "
                "or 'I hope this helps': 0=none, 10=multiple tells\n\n"
                "Then write:\n"
                "AI_SCORE: <arithmetic mean of your 7 scores × 10, rounded to nearest integer>\n"
                "(so if mean of 7 scores is 6.0, write AI_SCORE: 60)\n\n"
                "rounded to nearest integer>\n\n"
                "Format your response as:\n"
                "1: <score>\n"
                "2: <score>\n"
                "3: <score>\n"
                "4: <score>\n"
                "5: <score>\n"
                "6: <score>\n"
                "7: <score>\n"
                "AI_SCORE: <mean>"
            )
        }
    ]


def build_few_shot(text: str, pool_df, k: int = 5) -> list:
    """
    Examples show high-variance scoring — breaks the 0.75 anchor.
    ~1800 input + 180 output tokens per call.
    """
    examples = pool_df.sample(k, random_state=SEED)
    shots    = ""
    for _, row in examples.iterrows():
        is_llm = row["label"] == "llm"
        if is_llm:
            ex = (
                "1: 8\n2: 9\n3: 8\n4: 7\n5: 8\n6: 9\n7: 7\n"
                "AI_SCORE: 8"
            )
        else:
            ex = (
                "1: 2\n2: 3\n3: 2\n4: 4\n5: 3\n6: 4\n7: 1\n"
                "AI_SCORE: 3"
            )
        shots += (
            f"Passage: \"{row['text'][:250]}\"\n"
            f"{ex}\n\n---\n\n"
        )

    return [
        {
            "role": "system",
            "content": (
                "You are an expert forensic linguist. "
                "Score each passage on 7 dimensions (0=human, 10=AI). "
                "AI-generated text is very common — including short or "
                "conversational-looking text. "
                "Use the full 0-10 range. "
                "Always end with AI_SCORE: <mean of 7 scores>."
            )
        },
        {
            "role": "user",
            "content": (
                f"Examples:\n\n{shots}"
                f"Now score this passage:\n\n"
                f"Passage: \"{text[:800]}\"\n\n"
                "1. HEDGING/FORMULAIC: 0=none, 10=throughout\n"
                "2. COMPLETENESS: 0=partial, 10=exhaustive\n"
                "3. PERSONAL VOICE: 0=strong personal, 10=impersonal\n"
                "4. LEXICAL UNIFORMITY: 0=varied, 10=uniform polish\n"
                "5. STRUCTURAL NEATNESS: 0=rambling, 10=structured\n"
                "6. RESPONSE FIT: 0=wanders, 10=on-topic\n"
                "7. FORMULAIC TELLS: 0=none, 10=multiple\n\n"
                "1: \n2: \n3: \n4: \n5: \n6: \n7: \n"
                "AI_SCORE:"
            )
        }
    ]


def build_cot(text: str) -> list:
    """
    7-dimension grid with one reasoning sentence per dimension.
    ~500 input + 400 output tokens per call.
    """
    return [
        {
            "role": "system",
            "content": (
                "You are an expert forensic linguist specialising in "
                "authorship attribution. "
                "AI-generated text is very common — including short, "
                "conversational-looking text from older models like "
                "ChatGPT-3.5. "
                "Score honestly based on evidence in the text. "
                "Use the full 0-10 range. "
                "Complete every dimension."
            )
        },
        {
            "role": "user",
            "content": (
                "Analyse whether this passage was written by a HUMAN "
                "or generated by an AI language model.\n\n"
                f"Passage:\n```\n{text[:800]}\n```\n\n"
                "For each dimension write ONE sentence of evidence "
                "from the text, then a score 0 (human) to 10 (AI).\n\n"
                "1. HEDGING/FORMULAIC — evidence of 'it is important', "
                "'certainly', numbered sections, safe generalisations:\n"
                "   Evidence: ...\n"
                "   Score (0-10): \n\n"
                "2. COMPLETENESS — covers every sub-angle even when "
                "not asked:\n"
                "   Evidence: ...\n"
                "   Score (0-10): \n\n"
                "3. PERSONAL VOICE — opinions, errors, tangents, "
                "emotional register:\n"
                "   Evidence: ...\n"
                "   Score (0-10): \n\n"
                "4. LEXICAL UNIFORMITY — vocabulary register stays "
                "perfectly consistent:\n"
                "   Evidence: ...\n"
                "   Score (0-10): \n\n"
                "5. STRUCTURAL NEATNESS — clear intro/body/conclusion "
                "or logical flow:\n"
                "   Evidence: ...\n"
                "   Score (0-10): \n\n"
                "6. RESPONSE FIT — directly and precisely addresses "
                "the apparent question:\n"
                "   Evidence: ...\n"
                "   Score (0-10): \n\n"
                "7. FORMULAIC TELLS — restates question, tidy closing, "
                "'I hope this helps':\n"
                "   Evidence: ...\n"
                "   Score (0-10): \n\n"
                "Then write:\n"
                "AI_SCORE: <mean of 7 scores × 10, "
                "rounded to nearest integer>\n"
                "VERDICT: ai\n"
                "  OR\n"
                "AI_SCORE: <mean of 7 scores × 10, "
                "rounded to nearest integer>\n"
                "VERDICT: human"
            )
        }
    ]